apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: backend-dev
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30050
