apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dev
spec:
  selector:
    app: backend-dev
  ports:
    - name: http
      port: 5000          # Service port
      targetPort: 5000    # Container port
  type: ClusterIP
