apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dev
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-dev
  template:
    metadata:
      labels:
        app: frontend-dev
    spec:
      containers:
        - name: frontend
          image: us-central1-docker.pkg.dev/YOUR_GCP_PROJECT_ID/gke-apps/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
