apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev
spec:
  selector:
    app: frontend-dev
  ports:
    - name: http
      port: 80          # Service port
      targetPort: 8080    # Container port
  type: ClusterIP
