apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: frontend-dev
  ports:
    - port: 80           # service port
      targetPort: 8080   # container port
      nodePort: 30080    # fixed NodePort (must be 30000â€“32767)
