apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-ingress
  namespace: dev
  annotations:
    kubernetes.io/ingress.class: "gce"
    cloud.google.com/load-balancer-type: "Internal"
spec:
  backend:
    service:
      name: frontend-service
      port:
        number: 80
