apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
data:
  DB_USER: BASE64_ENCODED_DB_USER
  DB_PASSWORD: BASE64_ENCODED_DB_PASSWORD
  DB_NAME: BASE64_ENCODED_DB_NAME
